site_name: Mohammad_Robot

nav:
  - Home: index.md
  - Book:
      - AI in Robotics: Book/AI-in-Robotics.md
  - Robots:
      - Unitree G1: Robots/Unitree-G1.md
  - Projects:
      - ROS MasterClass Checkpoint 1: Porjects/CheckPointOne.md
  - ROS:
      - ROS 2 Basic: ROS/ROS-2-Basic.md
      - Gazebo Sim Harmonic + Humble: ROS/Gazebo-Sim-Harmonic-Humble.md
      - ROS 2 Control: ROS/ROS-2-Control.md
      - Orbbec Gemini E: ROS/Orbbec-Gemini-E.md
      - YDLIDAR T-mini: ROS/YDLIDAR-T-mini.md
      - Blender CAD Mesh Workflow: ROS/Blender-CAD-Meshes.md
      - WSL: ROS/WSL.md
      - Linux: ROS/Linex.md
      - CUDA: ROS/cuda.md

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/mohammad_robot
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/Mohammad.Robot
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mohammad_robot
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mohammad-robot/
    - icon: fontawesome/brands/github
      link: https://github.com/MohammadRobot

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    # See available fonts at https://fonts.google.com/
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: material/school
  favicon: images/favicon.svg
  features:
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - extra
  - smarty
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - attr_list
