site_name: Mohammad_Robot

nav:
  - Home: index.md
  - Book:
      - AI in Robotics: Book/AI-in-Robotics.md
  - Robots:
      - Unitree G1: Robots/Unitree-G1.md
  - Projects:
      - ROS MasterClass Checkpoint 1: Porjects/CheckPointOne.md
  - ROS:
      - ROS Basic: ROS/ROS-Basic.md
      - ROS 2 Basic: ROS/ROS-2-Basic.md
      - Orbbec Gemini E: ROS/Orbbec-Gemini-E.md
      - YDLIDAR T-mini: ROS/YDLIDAR-T-mini.md
      - Gazebo Sim Basics: ROS/Gazebo-Sim-Basics.md
      - Blender CAD Mesh Workflow: ROS/Blender-CAD-Meshes.md
      - Teleop: ROS/teleop.md
      - WSL: ROS/WSL.md
      - Linux: ROS/Linex.md
      - CUDA: ROS/cuda.md
      - Scan: ROS/scan.md

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/mohammad_robot
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/Mohammad.Robot
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mohammad_robot
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mohammad-robot/
    - icon: fontawesome/brands/github
      link: https://github.com/MohammadRobot

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: black 
    accent: black 
  font:
    # See available fonts at https://fonts.google.com/
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: material/school
  favicon: images/favicon.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - attr_list
